from generate import *

GOALS = [
	Goal('Find {0}', SelectN(5, (
		"Crafting Kit",
		"Tailoring Tools",
		"Golden Tailoring Tools",
		"Sewing Needle",
		"Great Rune of the Unborn",
		"Godrick's Great Rune",
		"Radahn's Great Rune",
		"Rykard's Great Rune",
		"Melania's Great Rune",
		"Mohg's Great Rune",
		"Morgott's Great Rune",
		"Golden Sewing Needle",
		"Serpent's Amnion",
		"Alexander's Innards",
		"Irina's Letter",
		"Amber Starlight",
		"Chrysalid's Memento",
		"Rya's Necklace",
		"Lord of Blood's Favour",
		"Dancer's Castanets",
		"Sellian Sealbreaker",
		"Iji's Confession",
		"Beast Eye",
		"Black Knife Print",
		"Fingerprint Grape",
		"Seluvis's Potion",
		"Valkyrie's Prosthetic",
		"Weathered Dagger",
		"Seluvis' Introduction",
		"Sellen's Primal Glintstone",
		"Finger Slayer Blade",
		"Carian Inverted Statue",
		"Mending Rune of Death",
		"Miniature Ranni",
		"Darkmoon Ring",
		"Ancient Dragon Prayerbook",
		"Fire Monk's Prayerbook",
		"Giant's Prayerbook",
		"Godskin Prayerbook",
		"Two Fingers Prayerbook",
		"Golden Order Principia",
		"Conspectus Scroll",
		"Royal House Scroll",
		"Academy Scroll",
		"5 Memory Stones",
		"8 Cracked Pots",
		"5 Ritual Pots",
		"5 Perfume Bottles",
		"2 Shabriri Grapes",
		"4 Celstial Dew",
		"8 Dragon Hearts",
		"3 Seedbed Curse",
		"7 Larval Tears",
		"5 Deathroot",
	))),
	Goal('Use all three Imbued Sword Keys'),
	Goal("Complete Thopp's Quest"),
	Goal("Upgrade two {0} to +9 or +24", SelectN(2, [
		"Daggers",
		"Straight Sword",
		"Greatswords",
		"Colossal Swords",
		"Thrust Swords",
		"Heavy Thrust Swords",
		"Curved Swords",
		"Curved Greatswords",
		"Katanas",
		"Twinblades",
		"Axes",
		"Greataxes",
		"Hammers",
		"Flails",
		"Great Hammers",
		"Colossal Weapons",
		"Spears",
		"Great Spears",
		"Halberds",
		"Reapers",
		"Whips",
		"Fists",
		"Claws",
		"Light Bows",
		"Bows",
		"Greatbows",
		"Glintstone Staff",
		"Sacred Seal"
	])),
	Goal("Restore {0} Great Runes", Range(2, 4)),
	Goal("Duplicate {0} Rememberances", Range(2, 4)),
	Goal("Complete {0}", SelectN(20, [
		"Coastal Cave",
		"Deathtouched Catacombs",
		"Forlorn Hound Evergaol",
		"Fringefolk Hero's Grave",
		"Limegrave Tunnels",
		"Groveside Cave",
		"Highroad Cave",
		"Murkwater Catacombs",
		"Murkwater Cave",
		"Stormhill Evergaol",
		"Castle Morne",
		"Earthbore Cave",
		"Impaler's Catacombs",
		"Morne Tunnel",
		"Tombsward Catacombs",
		"Tombsward Cave",
		"Weeping Evergaol",
		"Academy Crystal Cave",
		"Black Knife Catacombs",
		"Caria Manor",
		"Cliffbottom Catacombs",
		"Cuckoo's Evergaol",
		"Kingsrealm Ruins",
		"Malefactor's Evergaol",
		"Raya Lucaria Crystal Tunnel",
		"Ringleader's Evergaol",
		"Village of the Albinaurics",
		"Royal Grave Evergaol",
		"Abandoned Cave",
		"Caelem Ruins",
		"Divine Tower of Caelid",
		"Gael Tunnel",
		"Gaol Cave",
		"Sellia Crystal Tunnel",
		"Sellia, Town of Sorcery",
		"Sellia Evergaol",
		"War-dead Catacombs",
		"Altus Tunnel",
		"Auriza Hero's Grave",
		"Auriza Side Tomb",
		"Dominula",
		"Golden Lineage Evergaol",
		"Leyndell Catacombs",
		"Lux Ruins",
		"Mirage Rise",
		"Perfumer's Grotto",
		"Sainted Hero's Grave",
		"Sealed Tunnel",
		"The Shaded Castle",
		"Sage's Cave",
		"Seethewater Cave",
		"Wyndham Catacombs",
		"Dragonbarrow Cave",
		"Giant Jar's Ordeal",
		"Castle Sol",
		"Giant-Conquering Hero's Grave",
		"Lord Contender's Evergaol",
		"Spirit Caller's Cave",
		"Stargazer's Ruins",
		"Albinauric Rise",
		"Cave of the Forlorn",
		"Consecrated SF Catacombs",
		"Hidden Path to the Haligtree",
		"Yelough Anix Ruins",
	])),
	Goal("Defeat {0}", SelectN(15, [
		"Godrick",
		"Margit",
		"the Red Wolf of Radagon",
		"Renalla",
		"Magma Wyrm Makar",
		"Misbegotten + Crucible Boss",
		"Godskin Noble in VM",
		"Rykard",
		"Morgott",
		"Draconic Sentinel",
		"Valiant Gargoyles",
		"Ancestor Spirit",
		"Regal Ancestor Spirit",
		"Black Blade Kindred (DB)",
		"Black Blade Kindred (FL)",
		"three Erdtree Avatars",
		"Four Night's Cavalry",
		"Night's Cavalry Duo",
		"Flying Dragon Agheel",
		"Decaying Eczykes",
		"Borealis the Freezing Fog",
		"Flying Dragon Greyll",
		"Glintstone Dragon Adula",
		"Glintstone Dragon Smarag",
		"Great Wyrm Theodorix",
		"Three Deathbirds",
		"Three Death Rite Birds",
		"Three Tibia Mariner",
		"Two Putrid Avatars",
		"Three Bearing Hunters",
		"Dragonkin of Nokstella",
		"Crucible Knight Siluria",
		"Lichdragon Fortissax",
		"Fia's Champions",
		"Astel, Naturalborn of the Void",
		"Astel, Starts of Darkness",
		"Elden Beast",
		"Hoarah Loux",
		"Radahn",
		"Melania",
		"Mohg, Lord of Blood",
		"Wormface",
	])),
]