const OPTIONS = [
	new Option('Find {0}', N(4, [
		"Firekeeper's Eyes",
		"Soul a Firekeeper",
		"Dragon Torso Stone",
		"Dragon Head Stone",
		"Twinkling Dragon Torso Stone",
		"Twinkling Dragon Head Stone",
		"Coiled Sword Fragment",
	])),
	new Option('Defeat {0}', N(4, [
		"Horace the Hushed",
		"Anri of Astora",
		"Leohnard",
		"Sirris",
		"Both Hodrick Phantoms",
		"Creighton Twice",
		"Andre of Astora",
		"Longfinger Kirk"
	])),
	new Option('Defeat {0}', N(3, [
		"Both Farron Watchdogs before Abyss Watchers",
		"The Master before Vordt",
		"Both Cathedral Hollows before reaching Irithyll",
		"Alva",
		"Heysel",
		"Both Faraam Knights",
	])),

	

	new Option("Infuse a weapon with {0}", N(2, [
		"Heavy", 
		"Sharp", 
		"Blessed", 
		"Fire",
		"Chaos",
		"Deep",
		"Dark",
		"Simple",
		"Crystal",
		"Raw",
		"Refined",
		"Lightning",
		"Hollow"
	])),
	new Option("Defeat Champion Gundyr without Parrying"),
	new Option("Defeat DSA while having parried them in the same attempt"),
	new Option("Complete {0}'s Questline.", O(["Siegward", "Sirris", "Anri", "Greirat"])),
	new Option('Upgrade {0} {1}s to +9', N(2, [1, 2, 3, 4, 5]), 
		O([
			"Dagger",
			"Straight Sword",
			"Greatsword",
			"Ultra Greatsword",
			"Curved Sword",
			"Katana",
			"Curved Greatsword",
			"Piercing Sword",
			"Axe",
			"Greataxe",
			"Hammer",
			"Greathammer",
			"Fist or Claw",
			"Spear",
			"Halberd",
			"Reaper",
			"Whip",
			"Bow",
			"Greatbow",
			"Crossbow"
		])),
	new Option("Free Greirat."),
	new Option("Upgrade a Twinkling Weapon to +{0}", O([3, 4, 5])),
	new Option("Upgrade a Titanite Scale Weapon to +{0}", O([3, 4, 5])),
	new Option('Kill {0} Monstrosities of Sin', O([1, 2, 3, 4])),
	new Option('Kill {0} Pontiff Beasts', O([1, 2, 3])),
	new Option('Kill {0} Deep Accursed', O([1, 2])),
	new Option('Kill {0} Demons', O([1, 2, 3, 4])),
	new Option('Collect {0} Estus Shards', O([5, 6, 7, 8, 9, 10, 11])),
	new Option('Collect {0} Undead Bone Shards', O([5, 6, 7])),
	new Option('Possess {0} souls at some point', R(300000, 600000)),
	//new Option("Kill {0} unique Elder Ghru", O([2, 3, 4, 5])),
	//new Option("Kill {0} Unique Pontiff Knights", O([3, 4, 5])),
	//new Option("Kill {0} Unique Fire Witches", O([2, 3, 4])),
	//new Option("Kill {0} Unique Gargoyles", O([4, 5, 6])),
	//new Option("Kill {0} Mimics", O([3, 4, 5, 6, 7, 8, 9])),
	//new Option("Kill {0} Unique Greatsword Lothric Knights", O([2, 3, 4])),
	//new Option("Kill {0} Unique Lycanthropes", O([3, 4, 5])),
	//new Option("Kill {0} Ravenous Crystal Lizards", O([2, 3, 4])),
	//new Option("Kill {0} Crystal Lizards", O([5, 6, 7, 8])),
	//new Option("Kill {0} Bosses with Poison/Toxic", O([1, 2, 3])),
	new Option("Find {0}", N(5, [
		"a Dark Sigil",
		"Great Swamp Pyromancy Tome",
		"Lift Chamber Key",
		"Braille Tome of Carim",
		"Sage's Scroll",
		"Fire Keeper Soul",
		"Grave Key",
		"Londor Braille Divine Tome",
		"Deep Braille Divine Tome",
		"Carthus Pyromancy Tome",
		"Izalith Pyromancy Tome",
		"Loretta's Bone",
		"Quelana Pyromancy Tome",
		"Grave Warden Pyromancy Tome",
		"Golden Scroll",
		"Braille Divine Tome of Lothric",
		"Logan's Scroll",
		"Sword of Avowal",
		"Eyes of a Fire Keeper",
		"Crystal Scroll",
		"Hawkwood's Sword Grass",
		"Blood of the Dark Souls"
	])),
	new Option("Find {0}", N(6, [
		"Dagger",
		"Parrying Dagger",
		"Mail Breaker",
		"Bandit's Knife",
		"Rotten Ghru Dagger",
		"Corvian Greatknife",
		"Handmaid's Dagger",
		"Scholar Candlestick",
		"Tailbone Shortsword",
		"Brigand Twindaggers",
		"Harpe",
		"Aquamarine Dagger",
		"Shortsword",
		"Longsword",
		"Broadsword",
		"Broken Straight Sword",
		"Astora Straightsword",
		"Lothric Knight Sword",
		"Barbed Straight Sword",
		"Dark Sword",
		"Cleric's Candlestick",
		"Irithyll Straightsword",
		"Anri's Straight Sword",
		"Sunlight Straightsword",
		"Morion Blade",
		"Lothric's Holy Sword",
		"Gotthard Twinswords",
		"Valorheart",
		"Ringed Knight Straightsword",
		"Bastard Sword",
		"Claymore",
		"Hollowslayer Greatsword",
		"Firelink Greatsword",
		"Black Knight Sword",
		"Flamberge",
		"Executioner's Greatsword",
		"Wolf Knight's Greatsword",
		"Wolnir's Holy Sword",
		"Greatsword of Judgement",
		"Storm Ruler",
		"Moonlight Greatsword",
		"Twin Princes' Greatsword",
		"Drakeblood Greatsword",
		"Onyx Blade",
		"Gael's Greatsword",
		"Zweihander",
		"Greatsword",
		"Astora Greatsword",
		"Farron Greatsword",
		"Fume Ultra Greatsword",
		"Profaned Greatsword",
		"Cathedral Knight Greatsword",
		"Black Knight Greatsword",
		"Lorian's Greatsword",
		"Lothric Knight Greatsword",
		"Ringed Knight Paired Greatswords",
		"Crescent Moon Sword",
		"Scimitar",
		"Pontiff Knight Curved Sword",
		"Falchion",
		"Sellsword Twinblades",
		"Warden Twinblades",
		"Shotel",
		"Painting Guardian's Curved Sword",
		"Dancer's Enchanted Swords",
		"Storm Curved Sword",
		"Carthus Curved Sword",
		"Carthus Shotel",
		"Rotten Ghru Curved Sword",
		"Follower Sabre",
		"Demon's Scar",
		"Murakumo",
		"Exile Greatsword",
		"Old Wolf Curved Sword",
		"Carthus Curved Greatsword",
		"Harald Curved Greatsword",
		"Darkdrift",
		"Uchigatana",
		"Washing Pole",
		"Onikiri and Ubadachi",
		"Black Blade",
		"Chaos Blade",
		"Bloodlust",
		"Frayed Blade",
		"Estoc",
		"Rapier",
		"Rciards Rapier",
		"Crystal Sage's Rapier",
		"Irithyll Rapier",
		"Crow Quills",
		"Battle Axe",
		"Hand Axe",
		"Thrall Axe",
		"Brigand Axe",
		"Dragonslayer's Axe",
		"Butcher Knife",
		"Winged Knight Twinaxes",
		"Eleonara",
		"Man Serpent Hatchet",
		"Millwood Battle Axe",
		"Greataxe",
		"Dragonslayer Greataxe",
		"Demon's Greataxe",
		"Great Machete",
		"Yhorm's Great Machete",
		"Black Knight Axe",
		"Earth Seeker",
		"Club",
		"Drang Hammers",
		"Mace",
		"Morning STar",
		"Reinforced Club",
		"Heysel Pick",
		"Warpick",
		"Blacksmith Hammer",
		"Gargoyle Flame Hammer",
		"Great Mace",
		"Large Club",
		"Vordt's Great Hammer",
		"Morne's Great Hammer",
		"Great Wooden Hammer",
		"Great Club",
		"Smough's Great Hammer",
		"Old King's Great Hammer",
		"Pickaxe",
		"Dragon Tooth",
		"Spiked Mace",
		"Quakestone Hammer",
		"Ledo's Great Hammer",
		"Caestus",
		"Demon's Fist",
		"Dark Hand",
		"Claw",
		"Manikin Claws",
		"Crow Talons",
		"Arstor's Spear",
		"Dragon Twinspears",
		"Gargoyle Flame Spear",
		"Spear",
		"Tailbone Spear",
		"Pike",
		"Wingest Spear",
		"Four-Pronged Plow",
		"Saint Bident",
		"Rotten Ghru Spear",
		"Partizan",
		"Yorshka's Spear",
		"Dragonslayer Spear",
		"Dragonslayer Swordspear",
		"Golden Ritual Spear",
		"Soldering Iron",
		"Lothric Knight Longspear",
		"Greatlance",
		"Follower Javelin",
		"Lothric War Banner",
		"Ringed Knight spear",
		"Halberd Lucerne",
		"Winged Knight Halverd",
		"Red Hilted Halberd",
		"Glaive",
		"Crescent Axe",
		"Gundyr's Halbered",
		"Black Knight Glaive",
		"Immolation Tinder",
		"Splitleaf Greatsword",
		"Crucifix of the Mad King",
		"Great Scythe",
		"Pontiff Knight Scythe",
		"Great Corvian Scythe",
		"Friede's Great Scythe",
		"Whip",
		"Notched Whip",
		"Witch's Locks",
		"Spotted Whip",
		"Rose of Ariandel",
	])),
	new Option("Find the {0} set", N(2, [
		"Alva",
		"Drakeblood",
		"Maiden",
		"Antiquated",
		"Drang",
		"Master's",
		"Archdeacon",
		"Dragonscale",
		"Mirrah Chain",
		"Favour",
		"Dragonslayer",
		"Mirrah",
		"Sun",
		"Eastern",
		"Morne",
		"Thorns",
		"Elite Knight",
		"Nameless Knight",
		"Assassin",
		"Evangelist",
		"Northern Armor",
		"Black Hand",
		"Executioner",
		"Old Sorcerer",
		"Black Knight",
		"Exile",
		"Outrider",
		"Black Iron",
		"Fallen Knight",
		"Pale Shade",
		"Black Leather",
		"Faraam",
		"Painting Guard",
		"Black",
		"Fire Keeper",
		"Pontiff",
		"Brass",
		"Fire Witch",
		"Prayer",
		"Brigand",
		"Firelink",
		"Pyromancer",
		"Catarina",
		"Grave Warden",
		"Sellsword",
		"Cathedral Knight",
		"Gundyr",
		"Shadow",
		"Chain",
		"Hard Leather",
		"Silver Knight",
		"Cleric",
		"Havel",
		"Smough",
		"Conjurator",
		"Herald",
		"Sorcerer",
		"Sunless",
		"Jailer",
		"Court Sorcerer",
		"Cornyx",
		"Karla",
		"Sunset",
		"Dancer",
		"Knight",
		"Undead Legion",
		"Dark",
		"Leather",
		"Winged Knight",
		"Deacon",
		"Leonhard",
		"Wolf Knight",
		"Deserter",
		"Lorian",
		"Worker",
		"Lothric Knight",
		"Xanthous",
	])),
]

