const OPTIONS = [
	new Option('Find {0}', S([
		"Firekeeper's Eyes",
		"Soul a Firekeeper",
		"Dragon Torso Stone",
		"Dragon Head Stone",
		"Twinkling Dragon Torso Stone",
		"Twinkling Dragon Head Stone",
		"Coiled Sword Fragment",
	])),
	new Option("Complete Siegward's Questline."),
	new Option('Kill {0} Monstrosities of Sin', O([1, 2, 3])),
	new Option('Kill {0} Pontiff Beasts', O([1, 2, 3])),
	new Option('Kill {0} Deep Accursed', O([1, 2])),
	new Option('Kill {0} Demons', O([1, 2, 3, 4])),
	new Option('Find {0}', N(5, [
		'Irithyll Straight Sword',
		'Irithyll Rapier',
		"Anri's Straightsword",
		'Eleonara',
		'Sunlight Spear',
		'Crystal Soul Spear',
		'Soul Spear',
		'Great Chaos Fireball',
		'Chaos Bed Vestiges',
		'Great Sunlight Spear',
		'Great Sunlight Spear',
		"Scholar's Candlestick",
		"Tailbone Short Sword",
		"Harpe",
		"Aquamarine Dagger",
		"Sunlight Straight Sword",
		"Morion Blade",
		"Valorheart",
		"Greatsword of Judgement",
		"Moonlight Greatsword",
		"Twin Princes' Greatsword",
		"Onyx Blade",
		"Crescent Moon Sword",
		"Dancer's Enchanted Swords",
		"Storm Curved Sword",
		"Demon's Scar",
		"Bloodlust",
		"Frayed Blade",
		"Chaos Blade",
		"Crow Quills",
		"Yhorm's Great Machete",
		"Earth Seeker",
		"Heysel Pick",
		"Drang Hammers",
		"Morne's Greathammer",
		"Dragon Tooth",
		"Smough's Hammer",
		"Ledo's Great Hammer",
		"Demon's Fist",
		"Crow Talons",
		"Tailbone Spear",
		"Yorshka's Spear",
		"Dragonslayer Spear",
		"Dragonslayer Swordspear",
		"Soldering Iron",
		"Glaive",
		"Gundyr's Halberd",
		"Black Knight Glaive",
		"Splitleaf Greatsword",
		"Friede's Great Scythe",
		"Great Corvian Scythe",
		"Spotted Whip",
		"Rose of Ariandel",
		"Darkmoon Longbow",
		"Dragonrider Bow",
		"White Birch Bow",
		"Heretic's Staff",
		"Sage's Crystal Staff",
		"Izalith Staff",
		"Storyteller's Staff",
		"Archdeacon's Great Staff",
		"Preacher's Right Arm",
		"Pyromancer's Parting Flame",
		"Crystal Chime",
		"White Hair Talisman",
		"Caitha's Chime"
	])),
	new Option('Collect {0} Estus Shards', O([5, 6, 7, 8, 9, 10, 11, 12, 13, 14])),
	new Option('Collect {0} Undead Bone Shards', O([5, 6, 7, 8, 9])),
	new Option('Do not exceed level {0}', O([40, 50, 60, 70, 80])),
	new Option('Possess {0} souls at some point', R(100000, 400000)),
	new Option("Kill {0} Elder Ghru", O([1, 2, 3, 4, 5, 6])),
	new Option("Use {0}'s Soul", N(3, [
		"Vordt",
		"Greatwood",
		"Gundyr",
		"Pontiff",
		"Dancer",
		"DSA",
		"Oceiros",
		"Twin Princes",
		"Abyss Watchers",
		"Crystal Sage",
		"Wolnir",
		"Old Demon King",
		"Aldrich",
		"Yhorm",
		"Gael",
		"Midir",
		"Friede",
		"Deacon",
		"Nameless King",
		"Soul of Cinder"
	])),
	new Option("Defeat {0} with a {1} only", 
		O([
			"Soul of Cinder",
			"Vordt",
			"Greatwood",
			"Gundyr",
			"Pontiff",
			"Dancer",
			"DSA",
			"Oceiros",
			"Twin Princes",
			"Abyss Watchers",
			"Crystal Sage",
			"Wolnir",
			"Old Demon King",
			"Aldrich",
			"Yhorm",
			"Gael",
			"Midir",
			"Friede",
			"Deacon",
			"Nameless King",
			"Gravetender",
			"Ancient Wyver",
			"Halflight"
		]),
		O([
			"Dagger",
			"Straight Sword",
			"Greatsword",
			"Ultra Greatsword",
			"Curved Sword",
			"Katana",
			"Curved Greatsword",
			"Piercing Sword",
			"Axe",
			"Greataxe",
			"Hammer",
			"Greathammer",
			"Fist or Claw",
			"Spear",
			"Halberd",
			"Reaper",
			"Whip",
			"Bow",
			"Greatbow",
			"Crossbow",
			"Sorcery",
			"Pyromancy",
			"Miracle",
		])),
]

function main() {
	const bingo = new Bingo(OPTIONS);
	bingo.generate();
}

document.addEventListener('DOMContentLoaded', main, false);